# sample_1.0.0.yaml
#
info:
  version: 1.0.0
  title: fireforget
  description: sample laptop yaml
basePath: /fireforget
swagger: '2.0'
paths:
  /echo:
    get:
      responses:
        '200':
          description: 200 OK
x-ibm-configuration:
  assembly:
    execute:
       - fireforget:
          title: write a small json object
          source: "message.body = { text : 'Fire and Forget--> procesando...' };"
          url: "https://santanderconsumersandbox.eu-gb.mybluemix.net/fire"
schemes:
  - http